apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: registry.digitalocean.com/<your-registry>/todo-app:latest .
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DATABASE_URI
        resources:
          requests:
            cpu: 100m   
            memory: 
          limits:
            cpu: 500m 
